### ISSUE TITLE
can not use aptosclient.DialWithClient with httpProxy

### ISSUE THREAD

**Issue by dengcg0727** [coming-chat/go-aptos-sdk#3]
hi

My server can't access the internet without proxy

so I use  httpClientwith proxy setting in aptosclient.DialWithClient method

I can't use my proxy in the result:

Get "https://fullnode.devnet.aptoslabs.com/v1": dial tcp 52.12.208.71:443: i/o timeout

this is my code

     uri , _ := url.Parse("http://xxx.xxx.xxx.xxx:13080")
	httpClient := http.Client{
		Transport: &http.Transport{
			// proxy setting
			Proxy: http.ProxyURL(uri),
		},
	}
	
	restUrl := "https://fullnode.devnet.aptoslabs.com"
	
	client, err := aptosclient.DialWithClient(context.Background(), restUrl,&httpClient)
	if err != nil {
		logs.Error("aptosclient init error: ", err)
		return
	}
 
I guess the issue might cause in following:

func (c *RestClient) LedgerInfo() (res *aptostypes.LedgerInfo, err error) {
       // the http.NewRequest will be instead of the httpClient
	req, err := http.NewRequest("GET", c.GetVersionedRpcUrl(), nil)
	if err != nil {
		return
	}
	res = &aptostypes.LedgerInfo{}
	err = doReq(req, res)
	return
}

thanks

**Comment by xiang-xx** [comment]
Thanks for your issue. We will fix it. #4
